### ISSUE TITLE
Imagen RPI

### ISSUE THREAD

**Issue by rje1974** [GonzaCerv/noah-software#7]
Hola @GonzaCerv , estoy medio perdido.. Donde esta la imagen de ROS para la RPI o arranco de un ubuntu de cero y voy instalando.. Tambien pensando en el simulador debería ser noetic..? Saludos y gracias..

**Comment by GonzaCerv** [comment]
Hola @rje1974! De momento el software se armó para ros-melodic. Para poder ejecutar el software en el robot, debés quemar una imagen de Debian Buster en la Raspberry PI, instalar Docker y ejecutar `. noah_dev.sh`  del repo de [noah-docker](https://github.com/GonzaCerv/noah-docker).

**Comment by rje1974** [comment]
gracias, todo resuelto y la andando..

**Comment by GonzaCerv** [comment]
Cierro el hilo porque fue resuelto
